name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: 24

    - name: Setup Github user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Install dependencies
      run: npm install

    - name: Generate
      run: |
        node generate.js
        git add .
        git diff --staged --exit-code || (git commit -m 'ci(changelog): update version' && git push)

