name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: 24

    - name: Setup Github user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Install dependencies
      run: npm ci

    - name: Generate
      run: |
        node generate.js
#        git add .
#        git diff --staged --quiet || (git commit -m 'ci(changelog): generate timestamp' && git push)

    - name: Push gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        # Deploy keysやPersonal access Tokensも使用可能
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        # keep_filesをtrueにすると、git pushの度に一旦全てのファイルが削除される挙動を抑制できる
        # keep_files: true
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
